import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  safeArea: {
    flex: 1,
  },
  scroll: {
    paddingHorizontal: 20,
    paddingBottom: 40,
    gap: 24,
  },
  appTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#0F172A',
  },
  todayCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 32,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  todayLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
  },
  todayAmount: {
    fontSize: 72,
    fontWeight: '800',
    color: '#2563EB',
    lineHeight: 80,
  },
  todayUnit: {
    fontSize: 24,
    fontWeight: '600',
    color: '#64748B',
    marginTop: -8,
  },
  progressBarContainer: {
    width: '100%',
    marginTop: 24,
    marginBottom: 12,
  },
  progressBarBg: {
    width: '100%',
    height: 8,
    backgroundColor: '#E2E8F0',
    borderRadius: 999,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#2563EB',
    borderRadius: 999,
  },
  goalText: {
    fontSize: 14,
    color: '#64748B',
    fontWeight: '500',
    textAlign: 'center',
  },
  actions: {
    gap: 16,
  },
  sectionTitle: {
    fontSize: 16,
    color: '#0F172A',
    marginBottom: 4,
  },
  customTitle: {
    marginTop: 8,
  },
  presetsRow: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  presetBtn: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingVertical: 20,
    paddingHorizontal: 12,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 2,
    borderColor: '#E2E8F0',
  },
  presetAmount: {
    fontSize: 24,
    fontWeight: '700',
    color: '#2563EB',
  },
  presetLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
    marginTop: 2,
  },
  customRow: {
    flexDirection: 'row',
    gap: 12,
  },
  input: {
    flex: 1,
    height: 56,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    fontSize: 16,
    color: '#0F172A',
    fontWeight: '500',
    borderWidth: 2,
    borderColor: '#E2E8F0',
  },
  addBtn: {
    height: 56,
    paddingHorizontal: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2563EB',
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  addBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  pressed: {
    opacity: 0.7,
    transform: [{ scale: 0.98 }],
  },
  analytics: {
    gap: 16,
  },
  chartCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  chart: {
    height: 180,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 8,
  },
  barContainer: {
    alignItems: 'center',
    justifyContent: 'flex-end',
    flex: 1,
    gap: 6,
  },
  bar: {
    width: '100%',
    maxWidth: 32,
    backgroundColor: '#93C5FD',
    borderRadius: 8,
    minHeight: 8,
  },
  barToday: {
    backgroundColor: '#2563EB',
  },
  barValue: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748B',
  },
  barDate: {
    fontSize: 11,
    fontWeight: '600',
    color: '#94A3B8',
    fontVariant: ['tabular-nums'],
  },
  barDateToday: {
    color: '#2563EB',
    fontWeight: '700',
  },
  logo: {
    width: 50,
    height: 50,
    alignSelf: 'center',
  },
});
